import Head from "next/head";
import styles from "../../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Examples - Using Formulate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Examples</h1>

        <div className={styles.grid}>
          <a href="examples/simple-form" className={styles.card}>
            <h2>Simple form &rarr;</h2>
            <p>A simple form to show off the basics.</p>
          </a>
        </div>
      </main>
    </div>
  );
}
