import Head from "next/head";
import styles from "../../../styles/Home.module.css";

import { Formik, StringField } from "formulate";

export default function SimpleForm() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Simple form - Using Formulate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Simple form</h1>
        <Formik>
          <StringField name="Foo" />
        </Formik>
      </main>
    </div>
  );
}
