import Head from "next/head";
import styles from "../../../styles/Home.module.css";

import { Formik, Form, Field } from "formik";
import { TextField } from "formulate";

console.log(TextField);

export default function SimpleForm() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Simple form - Using Formulate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Simple form</h1>
        <Formik
          initialValues={{
            firstName: "",
            lastName: "",
            email: "",
          }}
          onSubmit={async (values) => {
            await new Promise((r) => setTimeout(r, 500));
            alert(JSON.stringify(values, null, 2));
          }}
        >
          <Form>
            <TextField name="firstName" label="First Name" placeholder="Jane" />

            <TextField name="lastName" label="Last Name" placeholder="Doe" />

            <TextField name="email" label="Email" placeholder="jane@acme.com" />
            <button type="submit">Submit</button>
          </Form>
        </Formik>{" "}
      </main>
    </div>
  );
}
